import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import {createApi} from './api.mjs';
test('server ownership, persistence, sessions, media and conflict protection',async()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-test-'));
 const seed=[{id:'seed',name:'Seed',latinName:'Seed',system:'System',subSystem:'Sub',description:'Test',imageUrl:'/anatomy/system-1.svg',mediaItems:[{id:'m',type:'2d_image',url:'/anatomy/system-1.svg'}],isFree:true,pins:[]}];
 let api=createApi({directory,seed,adminPassword:'test-admin-password',lecturerPassword:'test-dosen-password'});
 const outer=express();outer.use('/api',api.app);const server=outer.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const base=`http://127.0.0.1:${server.address().port}/api`;
 const request=async(url,method='GET',body,cookie='')=>{const res=await fetch(base+url,{method,headers:{'content-type':'application/json','X-Atlas-Request':'1',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};};
 try {
  assert.equal((await request('/users')).status,401);
  assert.equal((await request('/backup')).status,401);
  const admin=(await request('/auth/login','POST',{identifier:'admin',password:'test-admin-password'})).cookie;
  const dosen=(await request('/auth/login','POST',{identifier:'dosen',password:'test-dosen-password'})).cookie;
  assert.equal((await request('/auth/me','GET',undefined,dosen)).data.user.role,'DOSEN');
  assert.equal((await request('/organs/seed','PUT',{...seed[0],version:1},dosen)).status,403);
  const own=await request('/organs/own','PUT',{...seed[0],id:'own',ownerId:'admin-master',status:'draft'},dosen);assert.equal(own.status,200);assert.equal(own.data.ownerId,'dosen-paijo');
  assert.equal((await request('/organs/own')).status,404);
  assert.equal((await request('/organs/own','PUT',own.data,dosen)).data.version,2);
  assert.equal((await request('/organs/own','PUT',own.data,dosen)).status,409);
  assert.equal((await request('/organs/own?version=1','DELETE',undefined,dosen)).status,409);
  assert.equal((await request('/users/second','PUT',{name:'Second',email:'second',role:'DOSEN',password:'second-password'},admin)).status,200);
  const other=(await request('/auth/login','POST',{identifier:'second',password:'second-password'})).cookie;
  assert.equal((await request('/users','GET',undefined,other)).status,403);
  assert.equal((await request('/backup','GET',undefined,other)).status,403);
  assert.equal((await request('/organs/own','PUT',{...own.data,version:2},other)).status,403);
  assert.equal((await request('/organs/own?version=2','DELETE',undefined,other)).status,403);
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jX1sAAAAASUVORK5CYII=';
  const media=await request('/media','POST',{fileName:'test.png',category:'2d_image',base64:png},dosen);assert.equal(media.status,200);
  assert.equal((await request('/media/'+media.data.id+'/record','GET',undefined,other)).status,403);
  assert.equal((await request('/organs/stolen','PUT',{...seed[0],id:'stolen',imageUrl:media.data.blobUrl,mediaItems:[{id:'m',type:'2d_image',url:media.data.blobUrl}]},other)).status,403);
  assert.equal((await request('/settings/branding','PUT',{name:'New Atlas',description:'Test',logoUrl:''},dosen)).status,403);
  assert.equal((await request('/settings/branding','PUT',{name:'New Atlas',description:'Test',logoUrl:''},admin)).status,200);
  const backupResult=await fetch(base+'/backup',{headers:{Cookie:admin}});
  assert.equal(backupResult.status,200);
  const snapshot=Buffer.from(await backupResult.arrayBuffer());
  assert.equal(snapshot.subarray(0,15).toString(),'SQLite format 3');
  const forbidden=await fetch(base+'/auth/logout',{method:'POST',headers:{Cookie:dosen,'X-Atlas-Request':'1',Origin:'https://example.com'}});assert.equal(forbidden.status,403);
  assert.equal((await fetch(base+'/auth/logout',{method:'POST',headers:{Cookie:dosen}})).status,403);
  await request('/auth/logout','POST',undefined,dosen);assert.equal((await request('/auth/me','GET',undefined,dosen)).data.user,null);
  await new Promise(r=>server.close(r));api.db.close();api=createApi({directory,seed});
  assert.equal(api.db.prepare('SELECT version FROM organs WHERE id=?').get('own').version,2);
  assert.equal(api.db.prepare('SELECT count(*) AS n FROM media').get().n,1);
  assert.equal(JSON.parse(api.db.prepare("SELECT data FROM settings WHERE id='branding'").get().data).name,'New Atlas');
 } finally {if(server.listening)await new Promise(r=>server.close(r));api.db.close();const resolved=path.resolve(directory);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep+'atlas-test-'));fs.rmSync(resolved,{recursive:true,force:true});}
});
